data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
model_class_filename: model.py
model_class_name: Model
model_framework: sklearn
model_metadata:
  model_binary_dir: model
  supports_predict_proba: true
model_module_dir: model
model_name: null
model_type: Model
python_version: py39
requirements:
- joblib==1.1.0
- threadpoolctl==3.1.0
- scipy==1.8.1
- numpy==1.23.1
- scikit-learn==1.1.1
- bson==0.5.10
resources:
  cpu: 500m
  memory: 512Mi
  use_gpu: false
secrets: {}
system_packages: []
