bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
model_class_filename: model.py
model_class_name: Model
model_framework: sklearn
model_metadata:
  model_binary_dir: model
  supports_predict_proba: true
model_module_dir: model
model_name: null
model_type: Model
python_version: py38
requirements:
- appnope==0.1.3
- asttokens==2.0.5
- backcall==0.2.0
- baseten==0.2.1
- bson==0.5.10
- certifi==2022.6.15
- charset-normalizer==2.1.0
- click==8.1.3
- colorama==0.4.5
- coolname==1.1.0
- debugpy==1.6.2
- decorator==5.1.1
- entrypoints==0.4
- executing==0.9.0
- idna==3.3
- ipykernel==6.15.1
- ipython==8.4.0
- jedi==0.18.1
- Jinja2==3.1.2
- joblib==1.1.0
- jupyter-client==7.3.4
- jupyter-core==4.11.1
- MarkupSafe==2.1.1
- matplotlib-inline==0.1.3
- msgpack==1.0.4
- msgpack-numpy==0.4.8
- nest-asyncio==1.5.5
- numpy==1.23.1
- packaging==20.9
- parso==0.8.3
- pexpect==4.8.0
- pickleshare==0.7.5
- prompt-toolkit==3.0.30
- psutil==5.9.1
- ptyprocess==0.7.0
- pure-eval==0.2.2
- pydantic==1.9.1
- Pygments==2.12.0
- pyparsing==3.0.9
- python-dateutil==2.8.2
- python-json-logger==2.0.4
- python-on-whales==0.46.0
- PyYAML==6.0
- pyzmq==23.2.0
- requests==2.28.1
- requests-toolbelt==0.9.1
- scikit-learn==1.1.1
- scipy==1.8.1
- six==1.16.0
- sklearn==0.0
- stack-data==0.3.0
- tenacity==8.0.1
- threadpoolctl==3.1.0
- tornado==6.2
- tqdm==4.64.0
- traitlets==5.3.0
- truss==0.0.30
- typer==0.6.1
- typing_extensions==4.3.0
- urllib3==1.26.11
- wcwidth==0.2.5
resources:
  cpu: 500m
  memory: 512Mi
  use_gpu: false
secrets: {}
system_packages: []
